In [115]:
import pandas as pd
import numpy as np
from ib_insync import *
util.startLoop()  # uncomment this line when in a notebook
import datetime
import time
from IPython.display import display, clear_output
%matplotlib inline

In [117]:
# Connect with IB
# Please reach out to me directly if you need any detailed setup for IB API
ib = IB()
ib.connect('127.0.0.1', 7496, clientId=13)

In [118]:
df0 = pd.read_csv('SPY_20190101_.csv', index_col=0)
df0

                              time  bidSize     bid  askSize     ask
0        2019-01-02 09:00:00+00:00    500.0  244.51    500.0  245.43
1        2019-01-02 09:00:00+00:00    200.0  244.58    500.0  245.43
2        2019-01-02 09:00:00+00:00    100.0  245.50    100.0  251.05
3        2019-01-02 09:00:00+00:00    200.0  248.00    100.0  251.05
4        2019-01-02 09:00:00+00:00    200.0  248.00    100.0  249.79
...                            ...      ...     ...      ...     ...
7251590  2019-01-07 15:45:25+00:00   3000.0  253.76   1600.0  253.77
7251591  2019-01-07 15:45:25+00:00   3100.0  253.76   1600.0  253.77
7251592  2019-01-07 15:45:25+00:00   3200.0  253.76   1600.0  253.77
7251593  2019-01-07 15:45:25+00:00   3200.0  253.76   1500.0  253.77
7251594  2019-01-07 15:45:25+00:00   3000.0  253.76   1500.0  253.77

[7251595 rows x 5 columns]

In [119]:
# Define start time at any date but specify as shown below, accurate to second
# Leave end time as empty if you do not want to end at some point

start = datetime.datetime(2019, 1, 7, 15, 45, 26, tzinfo=datetime.timezone.utc)
# start = df.iloc[-1].time + datetime.timedelta(0,1)
end = ""
# start_time = time.time()
df = pd.DataFrame()

while start.replace(tzinfo=None) < datetime.datetime(2019, 1, 10):
    tickers = ib.reqHistoricalTicks(Stock('SPY', 'SMART', 'USD'), start, end, 1000, 'BID_ASK', useRth=False)
    for t in tickers:
        to_append = [t.time.isoformat(' ', 'seconds'), t.sizeBid, t.priceBid, t.sizeAsk, t.priceAsk]
        to_series = pd.Series(to_append)
        df = df.append(to_series, ignore_index=True, sort=False)
    start = tickers[-1].time + datetime.timedelta(0,1)

KeyboardInterrupt:

In [120]:
df

                                0       1       2       3       4
0       2019-01-07 15:45:25+00:00  3200.0  253.77  1200.0  253.78
1       2019-01-07 15:45:26+00:00  3400.0  253.77  1200.0  253.78
2       2019-01-07 15:45:26+00:00  3500.0  253.77  1200.0  253.78
3       2019-01-07 15:45:26+00:00  3500.0  253.77  1100.0  253.78
4       2019-01-07 15:45:26+00:00  3400.0  253.77  1100.0  253.78
...                           ...     ...     ...     ...     ...
622610  2019-01-07 16:40:16+00:00  1900.0  254.55   900.0  254.56
622611  2019-01-07 16:40:16+00:00  1900.0  254.55  1000.0  254.56
622612  2019-01-07 16:40:16+00:00  1900.0  254.55  1100.0  254.56
622613  2019-01-07 16:40:16+00:00  1900.0  254.55  1200.0  254.56
622614  2019-01-07 16:40:16+00:00  1900.0  254.55  1600.0  254.56

[622615 rows x 5 columns]

In [121]:
# Append new data collected to the origin dataset
df.columns=['time', 'bidSize', 'bid', 'askSize', 'ask']
df1 = df0.append(df, ignore_index=True)

In [124]:
df1

                              time  bidSize     bid  askSize     ask
0        2019-01-02 09:00:00+00:00    500.0  244.51    500.0  245.43
1        2019-01-02 09:00:00+00:00    200.0  244.58    500.0  245.43
2        2019-01-02 09:00:00+00:00    100.0  245.50    100.0  251.05
3        2019-01-02 09:00:00+00:00    200.0  248.00    100.0  251.05
4        2019-01-02 09:00:00+00:00    200.0  248.00    100.0  249.79
...                            ...      ...     ...      ...     ...
7874205  2019-01-07 16:40:16+00:00   1900.0  254.55    900.0  254.56
7874206  2019-01-07 16:40:16+00:00   1900.0  254.55   1000.0  254.56
7874207  2019-01-07 16:40:16+00:00   1900.0  254.55   1100.0  254.56
7874208  2019-01-07 16:40:16+00:00   1900.0  254.55   1200.0  254.56
7874209  2019-01-07 16:40:16+00:00   1900.0  254.55   1600.0  254.56

[7874210 rows x 5 columns]

In [125]:
# df.columns=['time', 'bidSize', 'bid', 'askSize', 'ask']
df1.to_csv('SPY_20190101_.csv')